Develop
illuminarean-internship/2023-summer-erp-front pull request #18
Opened 2023-07-18 03:18 UTC by juno-illuminarean

## Issue Ticket
- ITP2023-27 (Add navigation bar)
- ITP2023-29 (Login)
- ITP2023-15, ITP2023-5 (Overview Page)

## Summary
- ITP2023-27 (Add navigation bar)
Add navigation bar
- ITP2023-29 (Login)
Add next auth & login page & loading page
- ITP2023-15, ITP2023-5 (Overview Page)
Added category buttons and add new button feature.

## Detail Changes
- ITP2023-27 (Add navigation bar)
navigation bar added on top-level component _app.js
- ITP2023-29 (Login)
all pages protected by next-auth (google login)
before deploy, have to add and change .env file
ProtectedLayouts.js protect pages and used in _app.js
if user is not authenticated redirect to login page
- ITP2023-15, ITP2023-5 (Overview Page)
Added css to buttons according to figma

## Part/Question you would like to receive a review for
- is there any better way to protect pages before login?
- I adjusted the ratio with flexgrow in the navigation bar, but I wonder if there is a better way!
- Any feedback on the layout, coding structure, nomenclature, or possible bugs?

## Next to do
- working on sidebar menu, data table, navigation bar change (Junyub)
- Overview page, data table (Joshua)

2023-07-18 05:04 UTC, ilhyukKim requested changes

2023-07-18 05:04 UTC, ilhyukKim commented on src/components/AddCategoryButton.js
> +import DialogTitle from '@mui/material/DialogTitle';
`import {DialogTitle, DialogContentText, DialogContent, DialogActions, Dialog,TextField, Button} from '@mui/material';` 로 단축해서 쓰면 가독성이 좋아보일 수 있습니다 (이 부분은 기호차이에요)

그런데 mui에서 저 방법을 사용한 이유는  mui 라이브러리 자체가 사이즈가 너무 크기 때문입니다.
소개드린 방법을 사용하면 전체 라이브러리를 가져와서 빌드를 하기 때문에 용량문제가 생기기 때문이죠.
하지만 다행히도 바벨 플러그인을 사용해서 용량을 줄 일 수 있는데요, 아래 링크를 참고하시면 될 것 같습니다!
단순 공부용으로 참고만 하세요 ㅎㅎ

https://roseline.oopy.io/dev/optimize-bundle-size

2023-07-18 05:04 UTC, ilhyukKim commented on src/components/AddCategoryButton.js
> +    const [open, setOpen] = React.useState(false);
여기에서 `React.` 이 부분은 안 붙이셔도 됩니다.
React를 위에서 import 해서 사용하실 필요가 없기 때문입니다.
`import * as React from 'react';` 이 부분도 마찬가지입니다.

2023-07-18 05:04 UTC, ilhyukKim commented on src/pages/CategoryNavigationPage.js
CategoryNavigationPage 라는 네이밍이 부적합해보입니다.
http://localhost:3000/CategoryNavigationPage 로 넘어가야하는데 네이밍이 뭘 의미하는지 직관적으로 파악하기 힘들어보여요
add-category나 create-category 같은 네이밍이 좋아보입니다.
아니면 category에서 파생될거같으면 category 파일을 만들고 category 안에 add.jsx 로 넣으시는것도 좋은 방법일 것 같습니다.

2023-07-18 05:04 UTC, ilhyukKim commented on src/pages/CategoryNavigationPage.js
> +];
state에 컴포넌트를 담는게 부적합해보입니다.

```
const sampleStaringList = [
    {name: 'Accessory', link: 'test', size: 197},
    {name: 'Books', link: 'test', size: 90},
    {name: 'Desktop PC', link: 'test', size: 6},
    {name: 'Hardware', link: 'test', size: 99},
    {name: 'Mockups', link: 'test', size: 10},
    {name: 'Software', link: 'test', size: 9},
]
```
값만 전달해주시고 값을 컴포넌트에 렌더링하여 사용하시길 바랍니다.

2023-07-18 05:05 UTC, ilhyukKim commented on src/components/AddCategoryButton.js
> +        console.log('value is:', event.target.value);
console.log는 제거해주세요

2023-07-18 05:07 UTC, ilhyukKim commented on src/components/AddCategoryButton.js
> +    };
이런 값들은 useToggle 이나 useBoolean 같은 hook을 만들어 사용하시면 좋을 것 같아요

2023-07-18 05:11 UTC, ilhyukKim commented on src/components/CategoryButton.js
> +                    <img src="public/images/public/images/arrow.png" />
img 태그에는 alt attribute를 사용하셔야합니다.

https://www.w3schools.com/tags/att_img_alt.asp

2023-07-18 05:15 UTC, ilhyukKim commented on src/components/CategoryButton.js
> +const ButtonLinkStyleText = styled('div')`
이 부분은 통일성 있게 styled.div`` 가 맞아보입니다.
다른 styled component를 가져올때만 위 형식을 사용합니다.

ex)
```
const StyledBox = styled.div`
     ...
`

const StyledCategoryBox = styled(StyledBox)`
   ....
`
```

2023-07-18 05:17 UTC, ilhyukKim commented on src/components/AddCategoryButton.js
> +    const addItemToCategoryButtonList = () => {
이 부분도 https://github.com/illuminarean-internship/2023-summer-erp-front/pull/18/files#r1266227026 이 코멘트와 같이 컴포넌트를 배열에 추가하시는 방법이 아닌 , props로 전달할 값들을 추가해주세요 :)

2023-07-18 05:20 UTC, bomangoo requested changes

2023-07-18 05:20 UTC, bomangoo commented on src/pages/CategoryNavigationPage.js
> +                categoryButtonList={categoryButtonList}
categoryButtonList 이건 prop으로 넘길 필요가 없어 보입니다!

2023-07-18 05:20 UTC, bomangoo commented on src/components/AddCategoryButton.js
> +    const [open, setOpen] = React.useState(false);
state명 open은 의도가 명확치 않습니다. open 상태를 체크하려는 boolean의 state라면 isOpened로 변경하는 것이 좋겠습니다.

const [isOpenedState, setIsOpened] = useState(false);

2023-07-18 05:20 UTC, bomangoo commented on src/components/AddCategoryButton.js
> +        console.log('value is:', event.target.value);
머지할 때 consol은 지워주시기 바랍니다.

2023-07-18 05:22 UTC, ilhyukKim commented on src/components/Loading.js
> +                <img src="/images/logo.png" style={{ width: '350px' }} />
Next/Image의 Image 태그를 사용하시는걸 추천드립니다.
이미지는 import 하셔서 사용하시는게 좋을 것 같아요!

그리고 이 부분에서도 inline styling 보단 스타일드 컴포넌트를 활용하시는걸 권장합니다.


https://blog.logrocket.com/next-js-automatic-image-optimization-next-image/

2023-07-18 05:24 UTC, ilhyukKim commented on src/components/Navbar.js
> +import MoreIcon from '@mui/icons-material/MoreVert';
이 부분에서는 Loading.js 와 달른 방법으로 import를 하고 계시는데 통일성있게 사용하시면 더 좋을거같아요 ㅎㅎ

해당 코멘트 => https://github.com/illuminarean-internship/2023-summer-erp-front/pull/18/files#r1266214724

2023-07-18 05:24 UTC, bomangoo commented on src/pages/login.js
> +    console.log(session);
console.log 지워주세요

2023-07-18 05:27 UTC, bomangoo commented on src/pages/_app.js
> +                        <Navbar></Navbar>
<Navbar></Navbar> => <Navbar /> 로 줄일 수 있습니다

2023-07-18 05:27 UTC, kwonhygge commented on src/components/AddCategoryButton.js
> +export default function AddCategoryButton({
AddCategoryButton
라는 이름이 꼭 버튼 컴포넌트 같다는 생각이 드는데 안에 들어있는 내용은
카테고리 인풋 + 버튼 등 여러 내용이 담긴 것 같아서 조금 더 추상화된 이름으로 적어주면 좋을 것 같습니다!

2023-07-18 05:27 UTC, kwonhygge commented on src/components/CategoryButton.js
> +export default function CategoryButton({
category button 이라는 이름도 위의 AddCategoryButton과 같은 맥락에서 다른 이름을 고려해봐도 좋을 것 같습니다~ :)
CategoryButton이라기보다는 CategoryItem이라는 이름이 더 알맞을 것 같습니다.

2023-07-18 05:27 UTC, kwonhygge commented on src/components/CategoryButton.js
> +    width: 273px;
고정된 px 값을 사용하는 것보다 상대적인 rem을 사용하는 걸 권장드립니다~
rem을 사용하면 사용자가 브라우저 폰트크기를 조절할 수 있어서 사용자 편의를 위함입니다.
아래 아티클을 참고하시면 좋을 것 같습니다!

https://www.freecodecamp.org/news/why-use-rem-to-set-font-size-in-css/#:~:text=For%20styling%20a%20webpage%2C%20we,the%20size%20of%20the%20screen.

2023-07-18 05:27 UTC, kwonhygge commented on src/components/CategoryButton.js
> +    color: rgba(27, 27, 27, 0.62);
이 부분 figma에서 가져오신 것 같은데 rgba보다는 color code를 사용하기를 권장드리겠습니다~
자주 사용하는 색을 theme에 저장해놓고 사용하는걸 추천드려요.

2023-07-18 05:27 UTC, kwonhygge commented on src/components/CategoryButton.js
> +                    <img src="public/images/public/images/arrow.png" />
이미지가 안뜨고 있어서 확인해보시면 좋을 것 같습니다!

2023-07-18 05:31 UTC, ilhyukKim commented on src/pages/login.js
> +                <img src="/images/logo.png" style={{ width: '350px' }} />
img 대신 Next/Image태그를 사용하시길 권장드립니다.
그리고 이미지는 경로를 적기보단 import를 해와서 사용하시면 될거에요
alt도 있어야합니다!

[Next.js automatic image optimization with next/image - LogRocket Blog](https://blog.logrocket.com/next-js-automatic-image-optimization-next-image/)

2023-07-18 05:39 UTC, ilhyukKim commented on src/components/ProtectLayouts.js
> +            console.log('not authorized');
콘솔 제거 부탁드립니다!

2023-07-18 05:40 UTC, bomangoo commented on src/pages/_app.js
> +                {router.pathname !== '/login' ? (
router.pathname !== '/login' 분기처리는 < Navbar /> 안에서 정할 수 있습니다
`<ProtectLayouts>
                        <GlobalStyle />
                        {router.pathname !== '/login' && <Navbar/> }
                        <Component {...pageProps} />
                    </ProtectLayouts>`

2023-07-18 05:42 UTC, ilhyukKim commented on src/components/ProtectLayouts.js
> +    if (loading) {
Loading 같은 디테일함 너무 좋습니다 👍 👍 
이미지도 좋지만 아래와 같은 것도 고려해보시는것도 좋을 것 같아요
https://mui.com/material-ui/react-progress/

2023-07-18 05:43 UTC, ilhyukKim commented on src/pages/_app.js
> +                        <Component {...pageProps} />{' '}
{' '} 이 부분도 불필요하신 부분이면 지워주세요 ~!

2023-07-18 05:45 UTC, ilhyukKim commented on src/pages/login.js
> +                    onClick={() => signIn()}
onClick={signIn}으로 해주셔도 될거같아요~!

2023-07-18 05:46 UTC, bomangoo commented on src/pages/login.js
> +        <Loading></Loading>;
`<Loading />`

2023-07-18 05:47 UTC, kwonhygge commented on src/components/Navbar.js
> +                        <Link href={'/'}>
next link를 사용하실 때는 안에 a 태그를 넣어주세요~

https://stackoverflow.com/questions/63324839/why-using-a-tag-in-nextjs-link

2023-07-18 05:48 UTC, bomangoo commented on src/components/AddCategoryButton.js
> +    const addItemToCategoryButtonList = () => {
map을 이용해 반복문을 사용하시면 됩니다! 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2023-07-18 06:45 UTC, juno-illuminarean commented on src/pages/_app.js
> +                {router.pathname !== '/login' ? (
제 의도는 ProtectLayouts 컴포넌트로 감싸지는 것을 login 페이지에서만 제외하고 싶었습니다!(Navbar 또한 그렇습니다) 이 경우에는 어떻게 하는 것이 좋을까요?

2023-07-25 02:26 UTC, merged

2023-07-25 06:44 UTC, kwonhygge commented on src/components/Navbar.js
> +                        <Link href={'/'}>
아 이거 next 13부터는 안넣어도 된다고 하네요~ 참고 부탁드립니다!

2023-07-25 07:54 UTC, kwonhygge commented on src/components/CategoryItem.js
> +                        <img src={'/images/arrow.png'} alt="arrow.png" />
alt 태그는 이미지 내용을 설명해주는 게 더 좋습니다. 다른 이름으로 적어주면 더 나을 것 같습니다.
적으실 때 아래 링크를 참고해보세요.
https://help.siteimprove.com/support/solutions/articles/80000863904